services:
  resourcespace:
    build: .
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - filestore:/var/www/html/filestore
      - ./config.php:/var/www/html/include/config.php
      - /opt/rs_uploads:/mnt/imports
    networks:
      - frontend
      - backend
    ports:
      - "80:80"

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend

  nginx-proxy:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=aaron@theaccountingnerd.com
    volumes:
      - ./nginx_conf:/etc/nginx/user_conf.d
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - resourcespace

networks:
  frontend:
  backend:

volumes:
  mariadb:
  filestore:
